### ISSUE TITLE
training bug

### ISSUE THREAD

**Issue by fengwang99feng** [potsawee/longsum0#1]
I followed your step to preprocess data and train the basic bart model. It gave a bug as below. Any suggestions? @potsawee 

### Training Command

```python train/train_abssum.py conf/bart_arxiv_v0.txt```

### Output
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Traceback (most recent call last):
  File "train/train_abssum.py", line 197, in <module>
    run_training(sys.argv[1])
  File "train/train_abssum.py", line 121, in run_training
    loss = criterion(lm_logits.view(-1, bart_config.vocab_size), shifted_target_ids.view(-1))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 954, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2445, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2239, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1) to match target batch_size (177).

**Comment by potsawee** [comment]
Hi @fengwang99feng, 

Thanks for your interest in this repo! To answer your question, both the warning message and the error arise from the newer version of the transformers (HuggingFace) library. I was using transformers version 2.11.0, and it seems the newer versions 3+ have new APIs. And sorry that I did/do not have time to update this repo to be compatible with a more recent huggingface version.

To solve the issue when using newer version:

(1) "Truncation...." warning message. Please refer to this https://github.com/huggingface/transformers/issues/5397
In short, I believe just add ```truncation=True``` to tokenizer's calls.

(2) Error "ValueError: Expected input batch_size (1) to match target batch_size (177)."
In newer version, see this discussion https://discuss.huggingface.co/t/bartforconditionalgeneration-logits-shape-is-wrong-unexpected/2000

It seems the argument ```labels=...``` is required; thus, you need to modify the code as follows:

        x = bart_model(
            input_ids=input_ids, attention_mask=attention_mask,
            decoder_input_ids=target_ids, decoder_attention_mask=target_attention_mask,
            labels=shifted_target_ids,
        )

and the outputs of BART should now be:

        # x[0] # loss
        # x[1] # decoder output
        # x[2] # encoder output
        lm_logits = x[1]

e.g. you can change ```lm_logits``` to ```x[1]```, or simply use ```x[0]``` as the loss!

I hope this helps!
