### ISSUE TITLE
Is it possible to add a license for lobart's code and results?

### ISSUE THREAD

**Issue by Echoliu27** [potsawee/longsum0#10]
Hello, I'm trying to use your code and results in our team's research for summarization (comparison stage right now), but I'm not sure what's possible and what I can't.

Could you please specify which license is used for this project? i.e. MIT, Apache,...

Thank you

**Comment by potsawee** [comment]
Hello, 

thanks for asking. I just added the MIT license to the repository. Let me know if there is any issue.

Thanks
Potsawee

**Comment by Echoliu27** [comment]
Thanks for adding the license. Will close this issue.
