### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by fengwang99feng** [potsawee/longsum0#2]
Thank you for your great work!

I tried but cannot find the evlauation code to compute Rouge. Could you provide the code to reproduce the reported nubmers? @potsawee

**Comment by potsawee** [comment]
We use the ```pyrouge``` tool (https://pypi.org/project/pyrouge/) to compute ROUGE scores. Please download the tool from the link. You can follow this simple snippet to use ```pyrouge```:

    import sys
    from pyrouge import Rouge155

    def compute_rouge(system_dir, model_dir):

        r = Rouge155()
        r.system_dir = system_dir
        r.model_dir = model_dir

        r.system_filename_pattern = '(\d+)_decoded.txt'
        r.model_filename_pattern = '#ID#_reference.txt'

        output = r.convert_and_evaluate()
        print(output)
        # output_dict = r.output_to_dict(output)

    def main():
        if len(sys.argv) != 3:
            print('Usage: python3 rouge.py system_dir model_dir')
            return

        system_dir = sys.argv[1]
        model_dir  = sys.argv[2]

        compute_rouge(system_dir, model_dir)

    if __name__ == "__main__":
        main()
